# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/142mj-Rbxh5lscrPS9UlOO4XMiOQJaVbA
"""

import io
import random
import string # to process standard python strings
import warnings
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings('ignore')

import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('popular', quiet=True) # for downloading packages
#nltk.download('punkt') # first-time use only
#nltk.download('wordnet') # first-time use only

from google.colab import drive
drive.mount('/content/drive')

from glob import glob

f=open('/content/drive/MyDrive/chatbot.txt','r',errors = 'ignore')
raw=f.read()
raw = raw.lower()# converts to lowercase
raw

from google.colab import drive
drive.mount('/content/drive')

sent_tokens = nltk.sent_tokenize(raw)# converts to list of sentences 
word_tokens = nltk.word_tokenize(raw)# converts to list of words
word_tokens

lemmer = nltk.stem.WordNetLemmatizer()
#WordNet is a semantically-oriented dictionary of English included in NLTK.
def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
#The above code block will return a dictionary consisting of the integer codes of all punctuations in
#‘string.punctuation’ as keys and ‘None’ as values as shown below:
print(remove_punct_dict)

def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))
#In the following code block, we will define a method called LemNormalize to use the LemTokens function 
#and remove_punct_dict dictionary that we defined earlier for lemmatizing and to clean and tokenize the text.
#The translate method will convert all punctuations defined in the keys of 
#remove_punct_dict to their respective values which are None.

GREETING_INPUTS = ("hello", "hi", "greetings", "sup", "what's up","hey",)
GREETING_RESPONSES = ["hi", "hey", "*nods*", "hi there", "hello", "I am glad! You are talking to me"]
def greeting(sentence):
 
    for word in sentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)

def response(user_response):
    robo_response=''
    sent_tokens.append(user_response)

    TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
    # print("TfidfVec:", TfidfVec)
    # print("")
    # print("")


    tfidf = TfidfVec.fit_transform(sent_tokens)
    # print("tfidf: ",tfidf)
    # print("")
    # print("")


    vals = cosine_similarity(tfidf[-1], tfidf)
    # print("vals :",vals)
    # print("")
    # print("")



    idx=vals.argsort()[0][-2]
    # print("idx: ",idx)
    # print("")
    # print("")


    flat = vals.flatten()
    # print("flat: ",flat)
    # print("")
    # print("")

    flat.sort()

    req_tfidf = flat[-2]
    # print("req_tfidf : ",req_tfidf)
    # print("")
    # print("")

    
    if(req_tfidf==0):
        robo_response=robo_response+"I am sorry! I don't understand you"
        return robo_response
    else:
        robo_response = robo_response+sent_tokens[idx]
        return robo_response

flag=True
print("ROBO: My name is Robo. I will answer your queries about Chatbots. If you want to exit, type Bye!")
while(flag==True):
    user_response = input()
    user_response=user_response.lower()
    if(user_response!='bye'):
        if(user_response=='thanks' or user_response=='thank you' ):
            flag=False
            print("ROBO: You are welcome..")
        else:
            if(greeting(user_response)!=None):
                print("ROBO: "+greeting(user_response))
            else:
                print("ROBO: ",end="")
                print(response(user_response))
                sent_tokens.remove(user_response)
    else:
        flag=False
        print("ROBO: Bye! take care..")

